#!/bin/bash
apt-get update -y
apt install apache2 -y
apt update -y
add-apt-repository ppa:ondrej/php
DEBIAN_FRONTEND=noninteractive  apt-get --allow-unauthenticated -y install software-properties-common apt-utils tzdata 
add-apt-repository ppa:ondrej/php 
apt install php8.0 -y

##apt search php8.0-* 
apt install -y libapache2-mod-php \
  php8.0-common \
  php-cli \
  php-curl \
  php-mysql \
  php-gd \
  php-intl \
  php-xmlrpc \
  php-xml \
  php-mbstring \
  php-zip \
  php8.0-opcache \
  php-soap 
  php --version
